import { ROAST_COLORS, STATUS_COLORS } from "./constants";

export const styles = {
  root:            { display: "flex", height: "100vh", background: "#f5f0eb", color: "#2c1a0e", overflow: "hidden" },
  sidebar:         { width: 210, background: "linear-gradient(180deg, #1e3a1e 0%, #2d5a1b 100%)", display: "flex", flexDirection: "column" as const, padding: "24px 0", flexShrink: 0 },
  logo:            { padding: "0 20px 28px", borderBottom: "1px solid rgba(255,255,255,0.1)" },
  logoTitle:       { fontSize: 17, fontWeight: 700, color: "#f0e6d3", letterSpacing: "-0.3px" },
  logoSub:         { fontSize: 11, color: "rgba(240,230,211,0.55)", marginTop: 2 },
  nav:             { padding: "20px 12px", flex: 1, display: "flex", flexDirection: "column" as const, gap: 4 },
  navItem:         (active: boolean) => ({
    display: "flex", alignItems: "center", gap: 10, padding: "10px 12px",
    borderRadius: 8, cursor: "pointer", fontSize: 14, fontWeight: active ? 600 : 400,
    color: active ? "#f0e6d3" : "rgba(240,230,211,0.6)",
    background: active ? "rgba(255,255,255,0.12)" : "transparent",
    transition: "all 0.15s",
  }),
  navIcon:         { fontSize: 16 },
  sidebarBottom:   { padding: "16px 20px", borderTop: "1px solid rgba(255,255,255,0.1)" },
  sidebarLink:     { fontSize: 12, color: "rgba(240,230,211,0.5)", cursor: "pointer", display: "flex", alignItems: "center", gap: 6 },
  main:            { flex: 1, overflowY: "auto" as const, padding: "32px 36px" },
  pageHeader:      { marginBottom: 28 },
  pageTitle:       { fontSize: 26, fontWeight: 700, color: "#1e3a1e" },
  pageSubtitle:    { fontSize: 13, color: "#7a6a5a", marginTop: 4 },
  statGrid:        { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16, marginBottom: 32 },
  statCard:        { background: "#fff", borderRadius: 12, padding: "20px 22px", boxShadow: "0 1px 4px rgba(0,0,0,0.07)", border: "1px solid #e8e0d8" },
  statLabel:       { fontSize: 12, color: "#8a7a6a", fontWeight: 500, marginBottom: 8 },
  statValue:       { fontSize: 28, fontWeight: 700, color: "#1e3a1e", letterSpacing: "-1px" },
  statChange:      (pos: boolean) => ({ fontSize: 12, color: pos ? "#2e7d32" : "#c62828", marginTop: 6 }),
  card:            { background: "#fff", borderRadius: 12, boxShadow: "0 1px 4px rgba(0,0,0,0.07)", border: "1px solid #e8e0d8", overflow: "hidden" },
  cardHeader:      { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "18px 22px", borderBottom: "1px solid #f0ebe4" },
  cardTitle:       { fontSize: 15, fontWeight: 700, color: "#1e3a1e" },
  cardBadge:       { fontSize: 13, fontWeight: 600, color: "#5a8a3a" },
  table:           { width: "100%", borderCollapse: "collapse" as const },
  th:              { padding: "11px 16px", textAlign: "left" as const, fontSize: 12, fontWeight: 600, color: "#8a7a6a", background: "#faf6f2", borderBottom: "1px solid #ede7df", letterSpacing: "0.3px" },
  td:              { padding: "13px 16px", fontSize: 13, color: "#3a2a1a", borderBottom: "1px solid #f5f0eb" },
  statusBadge:     (status: string) => ({
    display: "inline-block", padding: "3px 10px", borderRadius: 20, fontSize: 12, fontWeight: 600,
    background: STATUS_COLORS[status]?.bg || "#f5f5f5",
    color: STATUS_COLORS[status]?.color || "#555",
  }),
  roastBadge:      (roast: string) => {
    const color = (ROAST_COLORS as Record<string, string>)[roast] ?? "#888";
    return {
      display: "inline-block", padding: "3px 10px", borderRadius: 20, fontSize: 12, fontWeight: 600,
      color,
      background: color + "18",
    };
  },
  topRow:          { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 28 },
  btn:             { padding: "9px 18px", borderRadius: 8, border: "none", cursor: "pointer", fontSize: 13, fontWeight: 600 },
  btnPrimary:      { background: "#2d5a1b", color: "#fff" },
  btnDanger:       { background: "#fce4ec", color: "#c62828", padding: "5px 12px", borderRadius: 6, border: "none", cursor: "pointer", fontSize: 12, fontWeight: 600 },
  btnEdit:         { background: "#e8f0fe", color: "#1565c0", padding: "5px 12px", borderRadius: 6, border: "none", cursor: "pointer", fontSize: 12, fontWeight: 600, marginRight: 6 },
  filterRow:       { display: "flex", alignItems: "center", gap: 12, padding: "14px 22px", borderBottom: "1px solid #f0ebe4", background: "#faf6f2" },
  filterLabel:     { fontSize: 13, color: "#6a5a4a", fontWeight: 500 },
  select:          { padding: "6px 12px", borderRadius: 6, border: "1px solid #ddd5cc", fontSize: 13, background: "#fff", color: "#3a2a1a", cursor: "pointer" },
  filterCount:     { marginLeft: "auto", fontSize: 13, color: "#8a7a6a" },
  dropdownWrapper: { position: "relative" as const, display: "inline-block" },
  dropdown:        { position: "absolute" as const, top: "100%", right: 0, background: "#fff", borderRadius: 8, boxShadow: "0 4px 16px rgba(0,0,0,0.12)", border: "1px solid #e0d8d0", zIndex: 100, minWidth: 120, padding: "4px 0" },
  dropdownItem:    { padding: "8px 14px", fontSize: 13, cursor: "pointer", color: "#3a2a1a" },
  tag:             { display: "inline-block", background: "#f0ebe4", color: "#5a4a3a", borderRadius: 4, padding: "2px 7px", fontSize: 11, marginRight: 4 },
  modal:           { position: "fixed" as const, inset: 0, background: "rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000 },
  modalBox:        { background: "#fff", borderRadius: 14, padding: "32px", width: 520, boxShadow: "0 8px 32px rgba(0,0,0,0.18)" },
  modalTitle:      { fontSize: 18, fontWeight: 700, color: "#1e3a1e", marginBottom: 24 },
  formGroup:       { marginBottom: 16 },
  formLabel:       { display: "block", fontSize: 12, fontWeight: 600, color: "#6a5a4a", marginBottom: 6 },
  formInput:       { width: "100%", padding: "8px 12px", borderRadius: 7, border: "1px solid #ddd5cc", fontSize: 13, boxSizing: "border-box" as const, outline: "none" },
  formRow:         { display: "flex", gap: 12 },
  formCheckbox:    { display: "flex", alignItems: "center", gap: 8, fontSize: 13, color: "#3a2a1a", cursor: "pointer" },
  modalActions:    { display: "flex", gap: 10, justifyContent: "flex-end", marginTop: 24 },
  btnCancel:       { padding: "9px 18px", borderRadius: 8, border: "1px solid #ddd5cc", cursor: "pointer", fontSize: 13, fontWeight: 600, background: "#fff", color: "#5a4a3a" },
  productCell:     { display: "flex", alignItems: "center", gap: 12 },
  productImg:      { width: 40, height: 40, borderRadius: 8, background: "#f0ebe4", objectFit: "cover" as const, flexShrink: 0 },
  productName:     { fontSize: 14, fontWeight: 600, color: "#2c1a0e" },
  productDesc:     { fontSize: 11, color: "#8a7a6a", marginTop: 2, maxWidth: 200, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" as const },
};
