import type { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "콜롬비아 나리뇨",
    price: 20000,
    weight: "250g",
    roasting: "미디엄",
    isDecaf: false,
    acidity: true,
    tags: ["미디엄", "산미"],
    shortDescription: "균형 잡힌 산미와 달콤한 과일향",
    thumbnailUrl: "/images/colombia-narino-thumb.png",
  },
  {
    id: 2,
    name: "브라질 세라 두 카파라오",
    price: 22000,
    weight: "250g",
    roasting: "다크",
    isDecaf: false,
    acidity: false,
    tags: ["다크"],
    shortDescription: "진한 초콜릿향과 묵직한 바디감",
    thumbnailUrl: "/images/brazil-thumb.png",
  },
  {
    id: 3,
    name: "콜롬비아 킨디오",
    price: 23000,
    weight: "250g",
    roasting: "라이트",
    isDecaf: false,
    acidity: true,
    tags: ["라이트", "산미"],
    shortDescription: "화이트와인 발효의 독특한 풍미",
    thumbnailUrl: "/images/colombia-quindio-thumb.png",
  },
  {
    id: 4,
    name: "에티오피아 시다모",
    price: 21000,
    weight: "250g",
    roasting: "라이트",
    isDecaf: true,
    acidity: true,
    tags: ["디카페인", "라이트", "산미"],
    shortDescription: "과일향 풍부한 에티오피아 디카페인 원두",
    thumbnailUrl: "/images/ethiopia-thumb.png",
  },
];
